;; Markdown memo
 
(defun markdown-memo-sendto-evernote ()
"Copy markdown file into evernote folder as text file."
(interactive)
(let* ((orgbuf (current-buffer))
(orgname (buffer-file-name))
(memonameorg (file-name-nondirectory orgname))
(memoname (concat (file-name-sans-extension memonameorg) ".txt"))
(destname (concat markdown-memo-evernote-dir memoname)))
(with-temp-buffer
(insert memonameorg)
(insert "\n")
(insert-buffer orgbuf)
(end-of-buffer)
;; (setq buffer-file-coding-system 'cp932)
(write-region (point-min) (point-max) destname)
)
)
)
(defun markdown-memo-create-memo ()
"Create new markdown memo file into specified folder."
(interactive)
(let* ((defaultfilename (format-time-string "%Y-%m-%d.md" (current-time)))
(orgname (read-string "memo file: " defaultfilename))
(memofile (concat markdown-memo-root-dir orgname)))
(find-file memofile)
)
)
(setq markdown-memo-root-dir "~/memo/")
(setq markdown-memo-evernote-dir "c:/Evernote/")
(global-set-key "\C-cse" 'markdown-memo-sendto-evernote)
(global-set-key "\C-cec" 'markdown-memo-create-memo)
