#!/bin/sh

## super userで実行する
BACKUPDATE=`date +%Y%m%d`
SAVE_DIR="/mnt/hdd01/download"

cd $SAVE_DIR

## /home 
tar czf home_bk_$BACKUPDATE.tar.gz /home --exclude ".local/share/Trash" --exclude Dropbox --exclude Download


## /etc
tar czf etc_bk_$BACKUPDATE.tar.gz /etc



## copy to ready nas ultra4
cp home_bk_$BACKUPDATE.tar.gz /mnt/readynas/backup/others/linux
cp etc_bk_$BACKUPDATE.tar.gz /mnt/readynas/backup/others/linux

